### ISSUE TITLE
Move github process in /adr to it's own page

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-architecture#6]
Github Process chapter in ADR page will be hard to reach as numbers of ADRs grow

**Comment by wtrocki** [comment]
Just an idea @tombentley

**Comment by wtrocki** [comment]
happy to do it if you agree

**Comment by tombentley** [comment]
Probably we need to rejig `/about`. so that it gives a very brief summary of the different document types and then we have `/about/adr`, `/about/padr` where we explain the process. That would mean we could remove `/process`, which would simplify the (top level of) navigation. Wdyt?

**Comment by wtrocki** [comment]
+1
